<?php

namespace ContainerBJWQBxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I3uGTsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I3uG_ts' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I3uG_ts'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', 'App\\Service\\Cart', 'getCartService', true],
            'product' => ['privates', '.errored..service_locator.I3uG_ts.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.I3uG_ts": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cart' => 'App\\Service\\Cart',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
