<?php

namespace ContainerBJWQBxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6vf7IPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B6vf7IP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B6vf7IP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartSession' => ['privates', 'App\\Service\\Cart', 'getCartService', true],
            'productRepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'cartSession' => 'App\\Service\\Cart',
            'productRepo' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
