controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login:
    path: /api/login
    methods: [POST]

api_doc:
    path: /
    controller: api_platform.swagger_ui.action