<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDK5lPe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDK5lPe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPDK5lPe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPDK5lPe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPDK5lPe\App_KernelDevDebugContainer([
    'container.build_hash' => 'PDK5lPe',
    'container.build_id' => '02562ec0',
    'container.build_time' => 1705219603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDK5lPe');
